# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(925, 736)
        self.centralwidget = QtWidgets.QWidget(HomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Tlwg Typist")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 3)
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.engine_select = QtWidgets.QComboBox(self.frame)
        self.engine_select.setObjectName("engine_select")
        self.engine_select.addItem("")
        self.engine_select.addItem("")
        self.gridLayout.addWidget(self.engine_select, 0, 1, 1, 1)
        self.csv_folder_select = QtWidgets.QPushButton(self.frame)
        self.csv_folder_select.setObjectName("csv_folder_select")
        self.gridLayout.addWidget(self.csv_folder_select, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 166, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.settings_button = QtWidgets.QPushButton(self.page)
        self.settings_button.setMinimumSize(QtCore.QSize(160, 131))
        self.settings_button.setMaximumSize(QtCore.QSize(16777215, 131))
        self.settings_button.setObjectName("settings_button")
        self.gridLayout_3.addWidget(self.settings_button, 3, 0, 1, 1)
        self.continue_to_app = QtWidgets.QPushButton(self.page)
        self.continue_to_app.setMinimumSize(QtCore.QSize(160, 131))
        self.continue_to_app.setMaximumSize(QtCore.QSize(16777215, 131))
        self.continue_to_app.setObjectName("continue_to_app")
        self.gridLayout_3.addWidget(self.continue_to_app, 3, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setMinimumSize(QtCore.QSize(160, 131))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 131))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 2, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.addMemberBtn = QtWidgets.QPushButton(self.page_2)
        self.addMemberBtn.setObjectName("addMemberBtn")
        self.gridLayout_4.addWidget(self.addMemberBtn, 0, 0, 1, 1)
        self.remove_member_btn = QtWidgets.QPushButton(self.page_2)
        self.remove_member_btn.setEnabled(False)
        self.remove_member_btn.setObjectName("remove_member_btn")
        self.gridLayout_4.addWidget(self.remove_member_btn, 0, 1, 1, 1)
        self.members_list = QtWidgets.QTableView(self.page_2)
        self.members_list.setEnabled(True)
        self.members_list.setObjectName("members_list")
        self.gridLayout_4.addWidget(self.members_list, 1, 0, 1, 2)
        self.add_payment_btn = QtWidgets.QPushButton(self.page_2)
        self.add_payment_btn.setEnabled(False)
        self.add_payment_btn.setObjectName("add_payment_btn")
        self.gridLayout_4.addWidget(self.add_payment_btn, 2, 0, 1, 1)
        self.statement_btn = QtWidgets.QPushButton(self.page_2)
        self.statement_btn.setEnabled(False)
        self.statement_btn.setObjectName("statement_btn")
        self.gridLayout_4.addWidget(self.statement_btn, 2, 1, 1, 1)
        self.view_all_payments = QtWidgets.QPushButton(self.page_2)
        self.view_all_payments.setObjectName("view_all_payments")
        self.gridLayout_4.addWidget(self.view_all_payments, 3, 0, 1, 2)
        self.run_backup = QtWidgets.QPushButton(self.page_2)
        self.run_backup.setObjectName("run_backup")
        self.gridLayout_4.addWidget(self.run_backup, 4, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        HomePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 22))
        self.menubar.setObjectName("menubar")
        HomePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomePage)
        self.statusbar.setObjectName("statusbar")
        HomePage.setStatusBar(self.statusbar)

        self.retranslateUi(HomePage)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "Home Page"))
        self.label_2.setText(_translate("HomePage", "SACCO YOURS LEDGER"))
        self.engine_select.setItemText(0, _translate("HomePage", "CSV Files"))
        self.engine_select.setItemText(1, _translate("HomePage", "MySQL Database(Requires Pre-Installed MySQL Database)"))
        self.csv_folder_select.setText(_translate("HomePage", "Folder..."))
        self.label_3.setText(_translate("HomePage", "Select CSV Folder"))
        self.label.setText(_translate("HomePage", "Select Storage Engine"))
        self.settings_button.setText(_translate("HomePage", "Settings"))
        self.continue_to_app.setText(_translate("HomePage", "Continue To App"))
        self.pushButton_3.setText(_translate("HomePage", "PushButton"))
        self.addMemberBtn.setText(_translate("HomePage", "Add People"))
        self.remove_member_btn.setText(_translate("HomePage", "Remove Selected"))
        self.add_payment_btn.setText(_translate("HomePage", "Add Payment for selected"))
        self.statement_btn.setText(_translate("HomePage", "Download Statement for selected"))
        self.view_all_payments.setText(_translate("HomePage", "View All Payments"))
        self.run_backup.setText(_translate("HomePage", "Backup"))

